### ISSUE TITLE
where cs project?

### ISSUE THREAD

**Issue by umarmining** [ivan-sincek/ransom-art#1]

**Comment by ivan-sincek** [comment]
Hi,

Sorry for the late response.

Unfortunately, there won't be any source code for the ransomware but I do plan to disclose some sandbox evasion techniques in the future.

You can check the [goliate/hidden-tear](https://github.com/goliate/hidden-tear) ransomware instead. I basically rewrote this ransomware from scratch, fixed some logic and weaponized it a little bit better, so you can try too.

P.S. Please use the open source malware responsibly.

Best regards,
Ivan.

**Comment by ivan-sincek** [comment]
I am closing this issue.
